# .github/.github/workflows/validate-tag-base.yml  (org meta‑repo)
name: Validate Tag
on:
  pull_request:

jobs:
  validate-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: |
          git fetch origin ${{ github.event.repository.default_branch }}
          if git merge-base --is-ancestor \
               origin/${{ github.event.repository.default_branch }} \
               ${{ github.sha }}; then
            echo "Tag is created from main branch ✔"
            exit 0
          else
            echo "::error::Tag is NOT created from main branch"
            exit 1
          fi
