# .github/.github/workflows/tag-guard.yml
name: tag-guard                       # ← this becomes the status‑check name
on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        required: true

jobs:
  verify-ancestor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }      # need full history for merge‑base
      - name: Fail if tag commit is NOT on main
        run: |
          set -e
          git fetch origin ${{ inputs.base_branch }}
          if git merge-base --is-ancestor origin/${{ inputs.base_branch }} ${{ github.sha }}; then
            echo "✅ Commit is already on ${{ inputs.base_branch }}"
          else
            echo "❌ Commit is NOT on ${{ inputs.base_branch }}"; exit 1
          fi
