# .github/.github/workflows/validate-tag-base.yml  (org meta‑repo)
name: Validate Commit For Tag Base

permissions:
  contents: read
  
on:
  workflow_call:

jobs:
  validate-commit-for-tag-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch default branch
        run: |
          echo "Default branch is ${{ github.event.repository.default_branch }}"
          git fetch origin ${{ github.event.repository.default_branch }}

      - name: Validate commit for tag
        run: |
          BASE=${{ github.event.repository.default_branch }}
          SHA=${{ github.sha }}

          if git merge-base --is-ancestor $SHA  origin/$BASE; then
            echo "✅ Commit $SHA is in $BASE."
          else
            echo "::error title=Tag validation dailed::Commit $SHA is NOT in $BASE."
            exit 1
          fi
