# .github/.github/workflows/validate-tag-base.yml  (org meta‑repo)
name: Validate Tag
on:
  pull_request:
  workflow_call:

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Default Branch
        run: |
          echo "Default branch is ${{ github.event.repository.default_branch }}"
          git fetch origin ${{ github.event.repository.default_branch }}

      - name: Validate 
        run: |
          BASE=${{ github.event.repository.default_branch }}
          SHA=${{ github.sha }}

          if git merge-base --is-ancestor origin/$BASE $SHA; then
            echo "✅ Commit $SHA is a descendant of $BASE."
          else
            echo "::error title=Tag Validation Failed::Commit $SHA is NOT based on $BASE."
            exit 1
          fi
